### ISSUE TITLE
Some objects have integers instead of property names

### ISSUE THREAD

**Issue by AdamGaskins** [Troposphir/AtmoSerialize#1]
For the first object (of a certain block I think) the property names are strings as they should be, but subsequent instances of that object have integers instead of strings as their property names.

**Comment by AdamGaskins** [comment]
To clarify they're all of type string of course, but the values are integers.

**Comment by kroltan** [comment]
The issue here is that property names are not currently available on the Preloads list.
I'm considering to make the preloads internal to the serialization, instead of a property of the `Map` itself, but this will require significant rework. Well, here I go!
